#chrome, firefox, safari
browser=chrome
headless = false
env = local
url = https://www.rbauction.com
qaurl= https://www.rbauction.com
timeout=20
enableProxy = false
proxyServer = 127.0.0.1
proxyServerPort = 9090
