name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'TestNG Suite File (e.g., testngTestAll.xml)'
        required: true
        default: 'testngTestAll.xml'
      headless:
        description: 'Run in Headless Mode? (Set to false to bypass "Action Denied")'
        required: true
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

#      - name: Run Maven Tests
#        # xvfb-run creates a virtual screen so "headless: false" works on CI
#        run: |
#          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" \
#          mvn clean test -DsuiteXmlFile=src/test/resources/${{ github.event.inputs.suite }} \
#          -Denv=ci \
#          -Dheadless=${{ github.event.inputs.headless }}
      - name: Run Maven Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/${{ github.event.inputs.suite }} -Denv=ci -Dheadless=${{ github.event.inputs.headless }}

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/surefire-reports
            target/test-output
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
      - name: Debug - List Reports
        if: always()
        run: ls -R target