name: Selenium Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testngTestAll.xml -Denv=ci

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/test-output